#!/bin/bash

# https://github.com/arkadyt/q3maps
# requires:
# * rsync and zip installed in the system.
# * The game itself (ioquake).
# bspc and q3map are included.

############################################################################
#                                                                          #
# This is a build script that does the following:                          #
#       * builds a full final BSP off of the .map file.                    #
#       * packages a .PK3 file and puts it into the baseq3 folder,         #
#         replacing the existing one                                       #
#       * synchronizes the map content into the baseq3 folder.             #
# I strongly recommend that you read (at least) the intro sections in      #
# both auxillary build scripts located in the ./aux-build-scripts          #
# to understand what is happening here and why.                            #
#                                                                          #
# Please configure the variables in the next section before executing it.  #
# Script also can be called with the following required arguments:         #
# $1    : game installation folder (the one holding baseq3 dir)            #
# $2    : map subfolder in the repository                                  #
# $3    : map file path in that subfolder                                  #
#                                                                          #
############################################################################



# configurable:
gameFolder=${1:-~/Games/q3.linux.ioq3.clean.excssmod/ioquake3_excessive}
mapFolder=${2:-$gameFolder/baseq3/q3maps/q3strong2018}
mapFilePath=${3:-$mapFolder/maps/q3strong2018.map}

# don't touch :)
repoRoot=$mapFolder/..
toolsFolder=$repoRoot/tools/linux
bspPath=${mapFilePath%.*}.bsp


# bspc and q3map2 are supplied with the GTKRadiant, q3map2 requires to be executed from the editor directory,
# because it needs some specific(?) libpng located next to it and won't pick up the one installed globally.
cd $toolsFolder/q3map2

# meta stage
# some people also use -patchmeta. Meta for curved patches?
./q3map2 -meta -fs_basepath $gameFolder $mapFilePath

# vis stage
# -saveprt              : saves visibility splitting into a file that can be viewed in the Radiant.
./q3map2 -vis -saveprt -fs_basepath $gameFolder $mapFilePath

# fast light
# ./q3map2 -light -fast -fs_basepath $gameFolder $mapFilePath 

# final light
# -shade                : enables phong shading
# -sky <n>              : multiplies the sky light value by <n>
# -pointscale <n.n>     : multiplies the point lights amount by <n.n>
# -gamma <n.n>          : increases gamma (used with _ambient:10 and a value of 1.4 in q3strong2018)
# -dirty                : enables ambient occlusion
# -samples <n>          : enables anti-aliasing
# -patchshadows         : cast and receive shadows for curves
# -fast                 : enables faster light calculation
# -bounce <n>           : enables radiosity effect
# -fs_basepath          : game folder location!
./q3map2 -light -fast -patchshadows -samples 6 -bounce 8 -gamma 1.4 -dirty -shade -fs_basepath $gameFolder $mapFilePath

cd $toolsFolder

# Build .aas files (Area Awareness System).
# -optimize             : reduces the .aas file size (sometimes x2 times)
# -forcesidesvisible    : have to be used if -meta switch is used
# -breadthfirst         : slightly faster aas build
./tbspc -optimize -forcesidesvisible -breadthfirst -bsp2aas $bspPath

echo done compiling, calling the packager...

# will package a .pk3 file and place it into the baseq3 directory
$repoRoot/tools/scripts/pk3build $mapFolder $gameFolder/baseq3
